apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment
  namespace: wanderlust

  labels:
    app: backend

#spec defines the desired state of the deployment
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend #deployment will find/manage pods with label app: backend

 #blueprint for creating pods
  template:

    metadata:
      labels:
        app: backend #deployment creates pod with label app: backend

    spec:
      containers:
        - name: backend

          image: izhank53/wanderlust-backend:latest

          ports:
            - containerPort: 5000

          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017

            - name: REDIS_URL
              value: redis://redis-service:6379

            - name: PORT
              value: "5000"


