apiVersion: v1
kind : PersistantVolumeClaim

metadata:
  name: mongo-pvc
  namespace: wanderlust

spec:
  accessModes:
    - ReadWriteOnce:


  resources:
    requests:
      storage: 5Gi

  storageClassName: standard