name: Wanderlust CI

on:
  push:
    branches: 
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backedn Docker image
        run: docker build -t wanderlust-backend:${{ github.sha }} ./backend/

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: wanderlust-backend:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Lint backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./backend/Dockerfile


  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build frontend docker image 
        run: docker build -t wanderlust-frontend:${{ github.sha }} ./frontend/

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: wanderlust-frontend:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Lint Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./frontend/Dockerfile
  
